package br.com.promocaosocial.model;
// Generated 29/06/2017 16:08:32 by Hibernate Tools 4.3.1



/**
 * Administrador generated by hbm2java
 */
public class Administrador  implements java.io.Serializable {


     private long id;
     private String nome;
     private String slide1a;
     private String slide1b;
     private String slide2a;
     private String slide2b;
     private String slide3a;
     private String slide3b;

    public Administrador() {
    }

    public Administrador(long id, String nome, String slide1a, String slide1b, String slide2a, 
            String slide2b, String slide3a, String slide3b) {
       this.id = id;
       this.nome = nome;
       this.slide1a = slide1a;
       this.slide1b = slide1b;
       this.slide2a = slide2a;
       this.slide2b = slide2b;
       this.slide3a = slide3a;
       this.slide3b = slide3b;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSlide1a() {
        return this.slide1a;
    }

    public void setSlide1a(String slide1a) {
        this.slide1a = slide1a;
    }

    public String getSlide1b() {
        return this.slide1b;
    }

    public void setSlide1b(String slide1b) {
        this.slide1b = slide1b;
    }

    public String getSlide2a() {
        return this.slide2a;
    }

    public void setSlide2a(String slide2a) {
        this.slide2a = slide2a;
    }

    public String getSlide2b() {
        return this.slide2b;
    }

    public void setSlide2b(String slide2b) {
        this.slide2b = slide2b;
    }

    public String getSlide3a() {
        return this.slide3a;
    }

    public void setSlide3a(String slide3a) {
        this.slide3a = slide3a;
    }

    public String getSlide3b() {
        return this.slide3b;
    }

    public void setSlide3b(String slide3b) {
        this.slide3b = slide3b;
    }
}


