package br.com.promocaosocial.model;
// Generated 29/06/2017 16:08:32 by Hibernate Tools 4.3.1



/**
 * Denunciaconselho generated by hbm2java
 */
public class Denunciaconselho  implements java.io.Serializable {


     private long id;
     private String nome;
     private String email;
     private String telefone;
     private String descricao;
     private String analise;
     private String tipo;
     
    public Denunciaconselho() {
    }

	
    public Denunciaconselho(long id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }
    public Denunciaconselho(long id, String nome, String email, String telefone, String descricao, String analise, String tipo) {
       this.id = id;
       this.nome = nome;
       this.email = email;
       this.telefone = telefone;
       this.descricao = descricao;
       this.analise = analise;
       this.tipo = tipo;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    public String getAnalise() {
        return this.analise;
    }
    
    public void setAnalise(String analise) {
        this.analise = analise;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }




}


