package br.com.promocaosocial.model;
// Generated 29/06/2017 16:08:32 by Hibernate Tools 4.3.1



/**
 * Oficina generated by hbm2java
 */
public class Oficina  implements java.io.Serializable {


     private long id;
     private String nome;
     private String descricao;
     private long vaga;
     private long cadastroreserva;

    public Oficina() {
    }

    public Oficina(long id, String nome, String descricao, long vaga, long cadastroreserva) {
       this.id = id;
       this.nome = nome;
       this.descricao = descricao;
       this.vaga = vaga;
       this.cadastroreserva = cadastroreserva;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public long getVaga() {
        return this.vaga;
    }
    
    public void setVaga(long vaga) {
        this.vaga = vaga;
    }
    public long getCadastroreserva() {
        return this.cadastroreserva;
    }
    
    public void setCadastroreserva(long cadastroreserva) {
        this.cadastroreserva = cadastroreserva;
    }




}


