package br.com.promocaosocial.model;
// Generated 29/06/2017 16:08:32 by Hibernate Tools 4.3.1



/**
 * Pessoasoficinas generated by hbm2java
 */
public class Pessoasoficinas  implements java.io.Serializable {


     private long id;
     private String nome;
     private String logradouro;
     private String bairro;
     private String cidade;
     private String numero;
     private String complemento;
     private String telefone;
     private String oficinaescolhida;
     private String cpf;
     private String status;

     
    public Pessoasoficinas() {
    }

    public Pessoasoficinas(long id, String nome, String logradouro, String bairro, String cidade, String numero, String complemento, String telefone, String oficinaescolhida, String cpf, String status) {
       this.id = id;
       this.nome = nome;
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.cidade = cidade;
       this.numero = numero;
       this.complemento = complemento;
       this.telefone = telefone;
       this.oficinaescolhida = oficinaescolhida;
       this.cpf = cpf;
       this.status = status;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }
    
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public String getOficinaescolhida() {
        return this.oficinaescolhida;
    }
    
    public void setOficinaescolhida(String oficinaescolhida) {
        this.oficinaescolhida = oficinaescolhida;
    }
    
    public String getCpf(){
        return this.cpf;
    }
    
    public void setCpf(String cpf){
        this.cpf = cpf;
    }
    
    public String getStatus(){
        return this.status;
    }
    
    public void setStatus(String status){
        this.status = status;
    }



}


