package br.com.promocaosocial.model;
// Generated 29/06/2017 16:08:32 by Hibernate Tools 4.3.1



/**
 * Servicosprestados generated by hbm2java
 */
public class Servicosprestados  implements java.io.Serializable {


     private long id;
     private Long atendimento;
     private Long atoinfracional;
     private Long denuncia;
     private Long encaminhamentopjud;
     private Long evasao;
     private Long indisciplina;
     private Long notificacao;
     private Long representacaompub;
     private Long requisaocreche;
     private Long requisicaosaude;
     private Long requisicaoservsocial;
     private Long requisicaoeducacao;
     private Long respostas;
     private Long solicitacaopm;
     private Long suspeitaabusosex;
     private Long suspeitamaustratos;
     private Long suspeitatrabinf;
     private Integer visitasdomi;
     private Long outrosserv;
     private Long plantao;
     private Long palestra;
     private Long acolhimento;
     private Long telefonesrecebido;
     private Long idaubs;
     private Long idaescola;
     private Long encaminhamentooficios;
     private String mesreferencia;

    public Servicosprestados() {
    }

	
    public Servicosprestados(long id) {
        this.id = id;
    }
    public Servicosprestados(long id, Long atendimento, Long atoinfracional, Long denuncia, Long encaminhamentopjud, Long evasao, Long indisciplina, Long notificacao, Long representacaompub, Long requisaocreche, Long requisicaosaude, Long requisicaoservsocial, Long requisicaoeducacao, Long respostas, Long solicitacaopm, Long suspeitaabusosex, Long suspeitamaustratos, Long suspeitatrabinf, Integer visitasdomi, Long outrosserv, Long plantao, Long palestra, Long acolhimento, Long telefonesrecebido, Long idaubs, Long idaescola, Long encaminhamentooficios, String mesreferencia) {
       this.id = id;
       this.atendimento = atendimento;
       this.atoinfracional = atoinfracional;
       this.denuncia = denuncia;
       this.encaminhamentopjud = encaminhamentopjud;
       this.evasao = evasao;
       this.indisciplina = indisciplina;
       this.notificacao = notificacao;
       this.representacaompub = representacaompub;
       this.requisaocreche = requisaocreche;
       this.requisicaosaude = requisicaosaude;
       this.requisicaoservsocial = requisicaoservsocial;
       this.requisicaoeducacao = requisicaoeducacao;
       this.respostas = respostas;
       this.solicitacaopm = solicitacaopm;
       this.suspeitaabusosex = suspeitaabusosex;
       this.suspeitamaustratos = suspeitamaustratos;
       this.suspeitatrabinf = suspeitatrabinf;
       this.visitasdomi = visitasdomi;
       this.outrosserv = outrosserv;
       this.plantao = plantao;
       this.palestra = palestra;
       this.acolhimento = acolhimento;
       this.telefonesrecebido = telefonesrecebido;
       this.idaubs = idaubs;
       this.idaescola = idaescola;
       this.encaminhamentooficios = encaminhamentooficios;
       this.mesreferencia = mesreferencia;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public Long getAtendimento() {
        return this.atendimento;
    }
    
    public void setAtendimento(Long atendimento) {
        this.atendimento = atendimento;
    }
    public Long getAtoinfracional() {
        return this.atoinfracional;
    }
    
    public void setAtoinfracional(Long atoinfracional) {
        this.atoinfracional = atoinfracional;
    }
    public Long getDenuncia() {
        return this.denuncia;
    }
    
    public void setDenuncia(Long denuncia) {
        this.denuncia = denuncia;
    }
    public Long getEncaminhamentopjud() {
        return this.encaminhamentopjud;
    }
    
    public void setEncaminhamentopjud(Long encaminhamentopjud) {
        this.encaminhamentopjud = encaminhamentopjud;
    }
    public Long getEvasao() {
        return this.evasao;
    }
    
    public void setEvasao(Long evasao) {
        this.evasao = evasao;
    }
    public Long getIndisciplina() {
        return this.indisciplina;
    }
    
    public void setIndisciplina(Long indisciplina) {
        this.indisciplina = indisciplina;
    }
    public Long getNotificacao() {
        return this.notificacao;
    }
    
    public void setNotificacao(Long notificacao) {
        this.notificacao = notificacao;
    }
    public Long getRepresentacaompub() {
        return this.representacaompub;
    }
    
    public void setRepresentacaompub(Long representacaompub) {
        this.representacaompub = representacaompub;
    }
    public Long getRequisaocreche() {
        return this.requisaocreche;
    }
    
    public void setRequisaocreche(Long requisaocreche) {
        this.requisaocreche = requisaocreche;
    }
    public Long getRequisicaosaude() {
        return this.requisicaosaude;
    }
    
    public void setRequisicaosaude(Long requisicaosaude) {
        this.requisicaosaude = requisicaosaude;
    }
    public Long getRequisicaoservsocial() {
        return this.requisicaoservsocial;
    }
    
    public void setRequisicaoservsocial(Long requisicaoservsocial) {
        this.requisicaoservsocial = requisicaoservsocial;
    }
    public Long getRequisicaoeducacao() {
        return this.requisicaoeducacao;
    }
    
    public void setRequisicaoeducacao(Long requisicaoeducacao) {
        this.requisicaoeducacao = requisicaoeducacao;
    }
    public Long getRespostas() {
        return this.respostas;
    }
    
    public void setRespostas(Long respostas) {
        this.respostas = respostas;
    }
    public Long getSolicitacaopm() {
        return this.solicitacaopm;
    }
    
    public void setSolicitacaopm(Long solicitacaopm) {
        this.solicitacaopm = solicitacaopm;
    }
    public Long getSuspeitaabusosex() {
        return this.suspeitaabusosex;
    }
    
    public void setSuspeitaabusosex(Long suspeitaabusosex) {
        this.suspeitaabusosex = suspeitaabusosex;
    }
    public Long getSuspeitamaustratos() {
        return this.suspeitamaustratos;
    }
    
    public void setSuspeitamaustratos(Long suspeitamaustratos) {
        this.suspeitamaustratos = suspeitamaustratos;
    }
    public Long getSuspeitatrabinf() {
        return this.suspeitatrabinf;
    }
    
    public void setSuspeitatrabinf(Long suspeitatrabinf) {
        this.suspeitatrabinf = suspeitatrabinf;
    }
    public Integer getVisitasdomi() {
        return this.visitasdomi;
    }
    
    public void setVisitasdomi(Integer visitasdomi) {
        this.visitasdomi = visitasdomi;
    }
    public Long getOutrosserv() {
        return this.outrosserv;
    }
    
    public void setOutrosserv(Long outrosserv) {
        this.outrosserv = outrosserv;
    }
    public Long getPlantao() {
        return this.plantao;
    }
    
    public void setPlantao(Long plantao) {
        this.plantao = plantao;
    }
    public Long getPalestra() {
        return this.palestra;
    }
    
    public void setPalestra(Long palestra) {
        this.palestra = palestra;
    }
    public Long getAcolhimento() {
        return this.acolhimento;
    }
    
    public void setAcolhimento(Long acolhimento) {
        this.acolhimento = acolhimento;
    }
    public Long getTelefonesrecebido() {
        return this.telefonesrecebido;
    }
    
    public void setTelefonesrecebido(Long telefonesrecebido) {
        this.telefonesrecebido = telefonesrecebido;
    }
    public Long getIdaubs() {
        return this.idaubs;
    }
    
    public void setIdaubs(Long idaubs) {
        this.idaubs = idaubs;
    }
    public Long getIdaescola() {
        return this.idaescola;
    }
    
    public void setIdaescola(Long idaescola) {
        this.idaescola = idaescola;
    }
    public Long getEncaminhamentooficios() {
        return this.encaminhamentooficios;
    }
    
    public void setEncaminhamentooficios(Long encaminhamentooficios) {
        this.encaminhamentooficios = encaminhamentooficios;
    }
    public String getMesreferencia() {
        return this.mesreferencia;
    }
    
    public void setMesreferencia(String mesreferencia) {
        this.mesreferencia = mesreferencia;
    }




}


