package br.com.promocaosocial.model;
// Generated 29/06/2017 16:08:32 by Hibernate Tools 4.3.1



/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private long id;
     private String nome;
     private String tipousuario;
     private String login;
     private String senha;
     

    public Usuario() {
    }

    public Usuario(long id, String nome, String tipousuario, String login, String senha) {
       this.id = id;
       this.nome = nome;
       this.tipousuario = tipousuario;
       this.login = login;
       this.senha = senha;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(String tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


